name: .NET CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest   # use Windows as required in the lab

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            7.0.x

      - name: Restore
        run: dotnet restore ICT3101_Calculator.sln

      - name: Build
        run: dotnet build ICT3101_Calculator.sln -c Release --no-restore

      # --- run NUnit tests ---
      - name: Run NUnit tests
        run: dotnet test ICT3101_CalculatorTest/ICT3101_Calculator.UnitTests.csproj -c Release --no-build --verbosity normal

      # --- run SpecFlow tests ---
      - name: Run SpecFlow tests
        run: dotnet test SpecFlowCalculatorTest/SpecFlowCalculatorTest.csproj -c Release --no-build --verbosity normal
